### ISSUE TITLE
No fields found with dynamoDB

### ISSUE THREAD

**Issue by ngladbach** [dacort/metabase-athena-driver#119]
Hey, we use the Athena plugin with dynamoDB together. Sync runs without a problem, but if I try to open the tables in metabase the logs show the following and no columns are shown:

```
022-11-14T14:52:21.017458606Z 2022-11-14 14:52:21,017 ERROR middleware.catch-exceptions :: Error processing query: No fields found for table "#########".
2022-11-14T14:52:21.017491189Z {:database_id #,
2022-11-14T14:52:21.017499022Z  :started_at #t "2022-11-14T14:52:20.850034Z[GMT]",
2022-11-14T14:52:21.017504156Z  :error_type :invalid-query,
2022-11-14T14:52:21.017508871Z  :json_query
2022-11-14T14:52:21.017513025Z  {:database #,
2022-11-14T14:52:21.017516611Z   :query {:source-table ###},
2022-11-14T14:52:21.017520585Z   :type "query",
2022-11-14T14:52:21.017524122Z   :parameters [],
2022-11-14T14:52:21.017528938Z   :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
2022-11-14T14:52:21.017533062Z  :native nil,
2022-11-14T14:52:21.017537098Z  :status :failed,
2022-11-14T14:52:21.017540979Z  :class clojure.lang.ExceptionInfo,
2022-11-14T14:52:21.017545375Z  :stacktrace
2022-11-14T14:52:21.017549296Z  ["--> query_processor.middleware.add_implicit_clauses$fn__52321$sorted_implicit_fields_for_table__52326$fn__52327.invoke(add_implicit_clauses.clj:47)"
2022-11-14T14:52:21.017554044Z   "query_processor.middleware.add_implicit_clauses$fn__52321$sorted_implicit_fields_for_table__52326.invoke(add_implicit_clauses.clj:41)"
2022-11-14T14:52:21.017559045Z   "query_processor.middleware.add_implicit_clauses$fn__52445$add_implicit_fields__52450$fn__52454.invoke(add_implicit_clauses.clj:107)"
2022-11-14T14:52:21.017563588Z   "query_processor.middleware.add_implicit_clauses$fn__52445$add_implicit_fields__52450.invoke(add_implicit_clauses.clj:100)"
2022-11-14T14:52:21.017567699Z   "query_processor.middleware.add_implicit_clauses$add_implicit_mbql_clauses$fn__52528.invoke(add_implicit_clauses.clj:150)"
2022-11-14T14:52:21.017571753Z   "query_processor.middleware.add_implicit_clauses$add_implicit_mbql_clauses.invokeStatic(add_implicit_clauses.clj:143)"
2022-11-14T14:52:21.017576216Z   "query_processor.middleware.add_implicit_clauses$add_implicit_mbql_clauses.invoke(add_implicit_clauses.clj:140)"
2022-11-14T14:52:21.017579762Z   "query_processor.middleware.add_implicit_clauses$add_implicit_clauses.invokeStatic(add_implicit_clauses.clj:160)"
2022-11-14T14:52:21.017583690Z   "query_processor.middleware.add_implicit_clauses$add_implicit_clauses.invoke(add_implicit_clauses.clj:154)"
2022-11-14T14:52:21.017588025Z   "query_processor$preprocess_STAR_$fn__54091.invoke(query_processor.clj:127)"
2022-11-14T14:52:21.017592301Z   "query_processor$preprocess_STAR_.invokeStatic(query_processor.clj:125)"
2022-11-14T14:52:21.017595907Z   "query_processor$preprocess_STAR_.invoke(query_processor.clj:120)"
2022-11-14T14:52:21.017599784Z   "query_processor$fn__54099$combined_pre_process__54100$combined_pre_process_STAR___54101.invoke(query_processor.clj:209)"
2022-11-14T14:52:21.017603365Z   "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__52544$fn__52549.invoke(resolve_database_and_driver.clj:35)"
2022-11-14T14:52:21.017607058Z   "driver$do_with_driver.invokeStatic(driver.clj:75)"
2022-11-14T14:52:21.017610702Z   "driver$do_with_driver.invoke(driver.clj:71)"
2022-11-14T14:52:21.017614750Z   "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__52544.invoke(resolve_database_and_driver.clj:34)"
2022-11-14T14:52:21.017634213Z   "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__48579.invoke(fetch_source_query.clj:353)"
2022-11-14T14:52:21.017640057Z   "query_processor.middleware.store$initialize_store$fn__48767$fn__48768.invoke(store.clj:11)"
2022-11-14T14:52:21.017651660Z   "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
2022-11-14T14:52:21.017657886Z   "query_processor.store$do_with_store.invoke(store.clj:38)"
2022-11-14T14:52:21.017664382Z   "query_processor.middleware.store$initialize_store$fn__48767.invoke(store.clj:10)"
2022-11-14T14:52:21.017670322Z   "query_processor.middleware.normalize_query$normalize$fn__52816.invoke(normalize_query.clj:22)"
2022-11-14T14:52:21.017677482Z   "query_processor.middleware.constraints$add_default_userland_constraints$fn__49849.invoke(constraints.clj:53)"
2022-11-14T14:52:21.017683045Z   "query_processor.middleware.process_userland_query$process_userland_query$fn__52755.invoke(process_userland_query.clj:145)"
2022-11-14T14:52:21.017689303Z   "query_processor.middleware.catch_exceptions$catch_exceptions$fn__53127.invoke(catch_exceptions.clj:167)"
2022-11-14T14:52:21.017695463Z   "query_processor.reducible$async_qp$qp_STAR___44982$thunk__44984.invoke(reducible.clj:100)"
2022-11-14T14:52:21.017701130Z   "query_processor.reducible$async_qp$qp_STAR___44982.invoke(reducible.clj:106)"
2022-11-14T14:52:21.017706802Z   "query_processor.reducible$async_qp$qp_STAR___44982.invoke(reducible.clj:91)"
2022-11-14T14:52:21.017713479Z   "query_processor.reducible$sync_qp$qp_STAR___44993.doInvoke(reducible.clj:126)"
2022-11-14T14:52:21.017717814Z   "query_processor$process_userland_query.invokeStatic(query_processor.clj:331)"
2022-11-14T14:52:21.017721962Z   "query_processor$process_userland_query.doInvoke(query_processor.clj:327)"
2022-11-14T14:52:21.017725647Z   "query_processor$fn__54146$process_query_and_save_execution_BANG___54155$fn__54158.invoke(query_processor.clj:342)"
2022-11-14T14:52:21.017733342Z   "query_processor$fn__54146$process_query_and_save_execution_BANG___54155.invoke(query_processor.clj:335)"
2022-11-14T14:52:21.017750470Z   "query_processor$fn__54190$process_query_and_save_with_max_results_constraints_BANG___54199$fn__54202.invoke(query_processor.clj:354)"
2022-11-14T14:52:21.017754723Z   "query_processor$fn__54190$process_query_and_save_with_max_results_constraints_BANG___54199.invoke(query_processor.clj:347)"
2022-11-14T14:52:21.017758471Z   "api.dataset$run_query_async$fn__68896.invoke(dataset.clj:69)"
2022-11-14T14:52:21.017762872Z   "query_processor.streaming$streaming_response_STAR_$fn__40100$fn__40101.invoke(streaming.clj:162)"
2022-11-14T14:52:21.017766680Z   "query_processor.streaming$streaming_response_STAR_$fn__40100.invoke(streaming.clj:161)"
2022-11-14T14:52:21.017770578Z   "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:65)"
2022-11-14T14:52:21.017774337Z   "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:63)"
2022-11-14T14:52:21.017777977Z   "async.streaming_response$do_f_async$task__19006.invoke(streaming_response.clj:84)"],
2022-11-14T14:52:21.017781675Z  :card_id nil,
2022-11-14T14:52:21.017785518Z  :context :ad-hoc,
2022-11-14T14:52:21.017789112Z  :error "No fields found for table \"#########\".",
2022-11-14T14:52:21.017792745Z  :row_count 0,
2022-11-14T14:52:21.017797048Z  :running_time 0,
2022-11-14T14:52:21.017800621Z  :preprocessed nil,
2022-11-14T14:52:21.017803918Z  :ex-data {:table-id ###, :type :invalid-query},
2022-11-14T14:52:21.017807712Z  :data {:rows [], :cols []}}
2022-11-14T14:52:21.017811223Z 

```

We are running Metabase v0.44.6 with athena plugin v1.5.1

If I use SQL statements I get results in Metabase.

**Comment by dacort** [comment]
@ngladbach Are there any other error messages?

**Comment by ngladbach** [comment]
I went through the logs and found the following:
```
Nov 16 12:24:15.832 WARN  49086 com.simba.athena.athena.core.AJConnection.connect: MinQueryExecPollingInterval configuration value needs to be positive.Setting to minimum value of 5 ms instead.
```
and
```
2022-11-16 12:24:15,547 WARN sync.util :: Error syncing Fields for Table 'Table ### 'default.##########''
java.sql.BatchUpdateException: Batch entry 0 UPDATE "metabase_field" SET "database_position" = 3, "name" = '########', "updated_at" = now() WHERE "id" = #### was aborted: ERROR: duplicate key value violates unique constraint "idx_uniq_field_table_id_parent_id_name_2col"
  Detail: Key (table_id, name)=(###, ########) already exists.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:52)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2367)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:560)
       ...
```
If this is not helpful I can start the rescan process again and check the logs?

**Comment by dacort** [comment]
Interesting...the `duplicate key value violates unique constraint` error indicates to me there might be some columns with the same name? I know that itself shouldn't be possible, but maybe there's a nested key that conflicts? I would see if there are any other logs that contain references to the athena driver, e.g. `metabase.driver.athena`.

That said, [Athena is officially supported by Metabase](https://www.metabase.com/releases/Metabase-0.45). Any future issues can be asked about on their [forum](https://discourse.metabase.com/) or with a detailed [bug report](https://github.com/metabase/metabase/issues). Will close this issue for now. :)
