### ISSUE TITLE
Building from source error

### ISSUE THREAD

**Issue by wnz99** [dacort/metabase-athena-driver#24]
Hi, 

I tried to build from source on Ubuntu 18.10 following the readme instructions, but got the following error. Unfortunately I've near 0 experience with building jar packages, so maybe it's something very obvious that I'm not doing correctly:

```
Applying task uberjar to []
Applying task javac to nil
Running javac with [-target 1.8 -source 1.8 @/tmp/.leiningen-cmdline15224665806995874236.tmp]
Applying task compile to nil
Compiling metabase.driver.athena
Syntax error compiling at (metabase/driver/athena.clj:142:1).
Exception in thread "main" Syntax error compiling at (metabase/driver/athena.clj:142:1).
        at clojure.lang.Compiler.analyze(Compiler.java:6808)
        at clojure.lang.Compiler.analyze(Compiler.java:6745)
        at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:986)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7106)
        at clojure.lang.Compiler.analyze(Compiler.java:6789)
        at clojure.lang.Compiler.analyze(Compiler.java:6745)
        at clojure.lang.Compiler.compile1(Compiler.java:7725)
        at clojure.lang.Compiler.compile(Compiler.java:7797)
        at clojure.lang.RT.compile(RT.java:415)
        at clojure.lang.RT.load(RT.java:461)
        at clojure.lang.RT.load(RT.java:428)
        at clojure.core$load$fn__6824.invoke(core.clj:6126)
        at clojure.core$load.invokeStatic(core.clj:6125)
        at clojure.core$load.doInvoke(core.clj:6109)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5908)
        at clojure.core$compile$fn__6829.invoke(core.clj:6136)
        at clojure.core$compile.invokeStatic(core.clj:6136)
        at clojure.core$compile.invoke(core.clj:6128)
        at user$eval155$fn__164.invoke(form-init282522768802351786.clj:1)
        at user$eval155.invokeStatic(form-init282522768802351786.clj:1)
        at user$eval155.invoke(form-init282522768802351786.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7176)
        at clojure.lang.Compiler.eval(Compiler.java:7166)
        at clojure.lang.Compiler.eval(Compiler.java:7166)
        at clojure.lang.Compiler.load(Compiler.java:7635)
        at clojure.lang.Compiler.loadFile(Compiler.java:7573)
        at clojure.main$load_script.invokeStatic(main.clj:452)
        at clojure.main$init_opt.invokeStatic(main.clj:454)
        at clojure.main$init_opt.invoke(main.clj:454)
        at clojure.main$initialize.invokeStatic(main.clj:485)
        at clojure.main$null_opt.invokeStatic(main.clj:519)
        at clojure.main$null_opt.invoke(main.clj:516)
        at clojure.main$main.invokeStatic(main.clj:598)
        at clojure.main$main.doInvoke(main.clj:561)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: No such var: driver/date-add
        at clojure.lang.Util.runtimeException(Util.java:221)
        at clojure.lang.Compiler.resolveIn(Compiler.java:7387)
        at clojure.lang.Compiler.resolve(Compiler.java:7357)
        at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7318)
        at clojure.lang.Compiler.analyze(Compiler.java:6768)
        ... 37 more
Compilation failed: Subprocess failed
```

**Comment by nicolasterral** [comment]
Did you download the Athena driver into your local Maven repo as explained in the readme?

Anyway, are you aware that you can download builded jars in the Releases section ?

**Comment by wnz99** [comment]
Yes I did. I did not notice the release section, I downloaded and installed successfully, many thanks.

**Comment by dacort** [comment]
Thanks for the help @nicolasterral! 

Going to leave this ticket open, though, as I want to validate the building from source instructions based on the `No such var: driver/date-add` error message.

**Comment by dacort** [comment]
Added a "Prerequisites" section to the readme as I just had to rebuild the repo from scratch and I had missed a couple things. Closing this out now as the README is more accurate.
