### ISSUE TITLE
consistent "Error syncing Fields for Table"

### ISSUE THREAD

**Issue by orenmazor** [dacort/metabase-athena-driver#61]
Hey @dacort, I started hitting this at some point in the recent past. 

I did some looking around and it seems like this is driver related. There's no trace I can provide you with right now, but here's a snippet of logs:

```
[9f6bbde4-1ab5-4d3e-abf5-c92e4b14d26c] 2020-08-31T09:00:05-04:00 INFO metabase.sync.util STARTING: step 'sync-timezone' for athena Database 3 'Datalake'
[9f6bbde4-1ab5-4d3e-abf5-c92e4b14d26c] 2020-08-31T09:00:06-04:00 INFO metabase.sync.util FINISHED: step 'sync-tables' for athena Database 3 'Datalake' (630.1 ms)
[9f6bbde4-1ab5-4d3e-abf5-c92e4b14d26c] 2020-08-31T09:00:06-04:00 INFO metabase.sync.util STARTING: step 'sync-fields' for athena Database 3 'Datalake'
[9f6bbde4-1ab5-4d3e-abf5-c92e4b14d26c] 2020-08-31T09:00:06-04:00 ERROR metabase.sync.util Error syncing Fields for Table foo```

```{
  "browser-info": {
    "language": "en-CA",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:79.0) Gecko/20100101 Firefox/79.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10",
    "os.name": "Linux",
    "os.version": "4.14.181-108.257.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "athena"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.8"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-08-17",
      "tag": "v0.36.4",
      "branch": "release-0.36.x",
      "hash": "196c1f6"
    },
    "settings": {
      "report-timezone": null
    }
  }
}```

**Comment by dacort** [comment]
Hi @orenmazor - Interesting, especially that there's no stack trace of any kind. A few questions:

- In your Athena console, do you see any queries that fail?
- Is the schema updating at all for either the specific table that errors or any of your tables?
- Anything funky with that specific table and it's data types? Can you query it with Athena?

**Comment by orenmazor** [comment]
> In your Athena console, do you see any queries that fail?

nope. its not getting to athena. my initial suspicion was an IAM issue around the user the driver is operating as, but that killed that :/

**Comment by dacort** [comment]
There were some IAM changes required in the most recent release (1.1.0) that I still need to document. Check out https://github.com/dacort/metabase-athena-driver/issues/56 to make sure you've got all the required permissions.

If it's not even getting to Athena, that's definitely weird. I'll check into some additional logging levels that might help today.

**Comment by orenmazor** [comment]
yeah I switched it to use my user (a localized administrator) to test that out and it was still the same error

**Comment by dacort** [comment]
Bummer, ok.

**Comment by dacort** [comment]
Here's some details for starting Metabase with some additional sync logging, lmk if anything useful shows up.

If you're running with the jar:
` java -Dlog4j.configuration=https://log4j.us/templates/metabase?trace=metabase.sync -jar metabase.jar`

If you're running with docker:
`docker run -e JAVA_OPTS=-Dlog4j.configuration=https://log4j.us/templates/metabase?trace=metabase.sync metabase/metabase`

**Comment by orenmazor** [comment]
I'm running in elasticbeanstalk, so I'll need to dig around to see how to set those. will report back

**Comment by orenmazor** [comment]
so, I couldn't set the above JAVA_OPTS env variable. EB seems to panic every time I apply it and revert.

but I did come across this in the logs:

```
09-01 19:00:26 [1mERROR sync.util[0m :: Error syncing Fields for Table 'Table 79 'datalake.accounts''
clojure.lang.ExceptionInfo: Output of table-metadata does not match schema: 

	 [0;33m  {:fields #{{:database-position missing-required-key}}} [0m 

	at metabase.sync.fetch_metadata$fn__52959$table_metadata__52964.invoke(fetch_metadata.clj:15)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__53281$db_metadata__53286$fn__53287.invoke(fetch_metadata.clj:86)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__53281$db_metadata__53286.invoke(fetch_metadata.clj:82)
	at metabase.sync.sync_metadata.fields$fn__53763$sync_fields_for_table_BANG___53772$fn__53775$fn__53776.invoke(fields.clj:75)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
	at metabase.sync.sync_metadata.fields$fn__53763$sync_fields_for_table_BANG___53772$fn__53775.invoke(fields.clj:74)
	at metabase.sync.sync_metadata.fields$fn__53763$sync_fields_for_table_BANG___53772.invoke(fields.clj:68)
	at clojure.core$partial$fn__5839.invoke(core.clj:2624)
	at clojure.core$map$fn__5866.invoke(core.clj:2753)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5402.invokeStatic(core.clj:137)
	at clojure.core$filter$fn__5893.invoke(core.clj:2809)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:58)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1792)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.sync.sync_metadata.fields$fn__53801$sync_fields_BANG___53806$fn__53807.invoke(fields.clj:88)
	at metabase.sync.sync_metadata.fields$fn__53801$sync_fields_BANG___53806.invoke(fields.clj:80)
	at metabase.sync.util$fn__42218$run_step_with_metadata__42223$fn__42227$fn__42229.invoke(util.clj:345)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:119)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:116)
	at metabase.sync.util$fn__42218$run_step_with_metadata__42223$fn__42227.invoke(util.clj:342)
	at metabase.sync.util$fn__42218$run_step_with_metadata__42223.invoke(util.clj:337)
	at metabase.sync.util$fn__42410$run_sync_operation__42415$fn__42416$fn__42417.invoke(util.clj:430)
	at clojure.core$mapv$fn__8445.invoke(core.clj:6912)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$mapv.invokeStatic(core.clj:6903)
	at clojure.core$mapv.invoke(core.clj:6903)
	at metabase.sync.util$fn__42410$run_sync_operation__42415$fn__42416.invoke(util.clj:430)
	at metabase.sync.util$fn__42410$run_sync_operation__42415.invoke(util.clj:424)
	at metabase.sync.sync_metadata$fn__54475$sync_db_metadata_BANG___54480$fn__54481$fn__54482.invoke(sync_metadata.clj:51)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:145)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
	at clojure.core$partial$fn__5839.invoke(core.clj:2623)
	at metabase.driver$fn__22445.invokeStatic(driver.clj:540)
	at metabase.driver$fn__22445.invoke(driver.clj:540)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__42130.invoke(util.clj:138)
	at metabase.sync.util$with_db_logging_disabled$fn__42127.invoke(util.clj:129)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
	at metabase.sync.util$with_start_and_finish_logging$fn__42116.invoke(util.clj:114)
	at metabase.sync.util$with_sync_events$fn__42111.invoke(util.clj:88)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__42102.invoke(util.clj:67)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:164)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:161)
	at metabase.sync.sync_metadata$fn__54475$sync_db_metadata_BANG___54480$fn__54481.invoke(sync_metadata.clj:50)
	at metabase.sync.sync_metadata$fn__54475$sync_db_metadata_BANG___54480.invoke(sync_metadata.clj:47)
	at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:42)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)

```

**Comment by dacort** [comment]
Which version of the Athena driver are you using?

**Comment by orenmazor** [comment]
Is there anywhere that I can confirm that it's loading the right thing? 

```
[4dc0d7f5-2a3f-4193-950a-d35c7daa69b0] 2020-09-01T15:00:13-04:00 INFO metabase.driver.impl Initializing driver :athena...
[4dc0d7f5-2a3f-4193-950a-d35c7daa69b0] 2020-09-01T15:00:13-04:00 DEBUG metabase.plugins.init-steps Loading plugin namespace metabase.driver.athena...
[4dc0d7f5-2a3f-4193-950a-d35c7daa69b0] 2020-09-01T15:00:13-04:00 INFO metabase.plugins.classloader Added URL file:/plugins/athena.metabase-driver.jar to classpath
[4dc0d7f5-2a3f-4193-950a-d35c7daa69b0] 2020-09-01T15:00:13-04:00 INFO metabase.driver.impl Registered abstract driver :metabase.driver.sql-jdbc.execute.legacy-impl/use-legacy-classes-for-read-and-set  🚚
[4dc0d7f5-2a3f-4193-950a-d35c7daa69b0] 2020-09-01T15:00:13-04:00 INFO metabase.driver.impl Registered driver :athena (parents: [:sql-jdbc :metabase.driver.sql-jdbc.execute.legacy-impl/use-legacy-classes-for-read-and-set]) 🚚```

**Comment by dacort** [comment]
Unfortunately not. The 1.1.0 version was released on Aug 2, so if you haven't updated the `athena.metabase-driver.jar` since then, you're probably running an old version.

**Comment by orenmazor** [comment]
I blew my entire deployment away and redeployed and the error appears to be gone.

curious.

**Comment by dacort** [comment]
Curious what your Dockerfile looks like? e.g. how you're getting the Athena jar into the environment?

I hadn't quite nailed down deployment mechanisms and it's pretty confusing which version of the driver goes with which version of Metabase.

**Comment by orenmazor** [comment]
just this that I stole from you:

```
FROM metabase/metabase:v0.36.4

# A metabase user/group is manually added in https://github.com/metabase/metabase/blob/master/bin/docker/run_metabase.sh
# Make the UID and GID match
ADD --chown=2000:2000 \
    https://github.com/dacort/metabase-athena-driver/releases/download/v1.1.0/athena.metabase-driver.jar \
    /plugins/athena.metabase-driver.jar

EXPOSE 3000
```

**Comment by dacort** [comment]
Curious indeed. 🤔 You're definitely pulling in the correct version there, so not sure what would have happened. The error message was consistent with new functionality in 0.36 (data model column reordering) not being addressed by the driver.

Glad it's working again though. Darn ghosts in the machine.

**Comment by orenmazor** [comment]
if I had to guess, I fucked up the deploy somewhere and couldn't prove that I had the latest version of things.

something to consider: driver dependency checks. i.e. "36.0 requires 1.1.0" or something :/
