### ISSUE TITLE
Metabase v0.40.1 does not sync

### ISSUE THREAD

**Issue by dacort** [dacort/metabase-athena-driver#86]
In attempting to do a fresh sync with Metabase v0.40.1, I receive errors both from Athena and Metabase.

A fresh sync works fine in Metabase v0.38.5, although there are warnings because I have some intentionally broken things:

```
2021-08-02 17:07:49,419 WARN driver.athena :: Don't know how to map column type 'Oops' to a Field base_type, falling back to :type/*.
java.sql.SQLException: [Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. HIVE_METASTORE_ERROR: Error: type expected at the position 0 of 'Oops' but 'Oops' is found. (Service: null; Status Code: 0; Error Code: null; Request ID: null; Proxy: null) [Execution ID: e2bf9367-a967-4b84-8523-fdcc4af433bf]
```

I also have some data connectors in my account that I think may be breaking things in 0.40, but at least in 0.38.5 the good tables show up. Nothing shows up at all in v0.40.

```
Caused by: com.simba.athena.support.exceptions.GeneralException: [Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. Failed to invoke lambda function due to com.amazonaws.services.lambda.model.AWSLambdaException: INFO: Lambda is initializing your function. It will be ready to invoke shortly. (Service: AWSLambda; Status Code: 500; Error Code: CodeArtifactUserPendingException; Request ID: 0d32f5e3-4bb0-4937-826f-b43fb1212eb2; Proxy: null) [Execution ID not available]
```

```
2021-08-02 16:58:52,142 WARN sync.util :: Error in sync step Sync metadata for athena Database 2 'Athena'
java.lang.ClassCastException: class java.sql.SQLException cannot be cast to class clojure.lang.Associative (java.sql.SQLException is in module java.sql of loader 'platform'; clojure.lang.Associative is in unnamed module of loader 'app')
        at clojure.lang.RT.assoc(RT.java:827)
        at clojure.core$assoc__5416.invokeStatic(core.clj:193)
        at clojure.core$assoc__5416.doInvoke(core.clj:190)
        at clojure.lang.RestFn.invoke(RestFn.java:573)
        at metabase.sync.util$fn__40212$run_step_with_metadata__40217$fn__40221.invoke(util.clj:366)
```

**Comment by dacort** [comment]
Nevermind, seems to work now - I think I mis-packaged v1.2.0.
