### ISSUE TITLE
Failing To Load Athena Driver

### ISSUE THREAD

**Issue by drew-flintosh** [dacort/metabase-athena-driver#88]
I've just started using Metabase and came across your repo trying to setup an Athena data source. Thanks for the work, btw. 

I believe I've set everything up as described in the README using the Docker image with the one exception I'm trying to use the latest release of Metabase v0.40.2. I can see the following errors in the logs when I try to create an Athena database. Is there a workaround you could suggest other than trying this with an older version of Metabase? 

```
6251-4a47-b042-cb2408e18c67] 2021-08-17T17:58:21-05:00 INFO metabase.driver.impl Initializing driver :athena...
[b3666a63-6251-4a47-b042-cb2408e18c67] 2021-08-17T17:58:21-05:00 INFO metabase.plugins.classloader Added URL file:/plugins/athena.metabase-driver.jar to classpath
[b3666a63-6251-4a47-b042-cb2408e18c67] 2021-08-17T17:58:21-05:00 DEBUG metabase.plugins.init-steps Loading plugin namespace metabase.driver.athena...
[b3666a63-6251-4a47-b042-cb2408e18c67] 2021-08-17T17:58:22-05:00 INFO metabase.driver.impl Registered abstract driver :metabase.driver.sql-jdbc.execute.legacy-impl/use-legacy-classes-for-read-and-set  🚚
[b3666a63-6251-4a47-b042-cb2408e18c67] 2021-08-17T17:58:22-05:00 INFO metabase.driver.impl Registered driver :athena (parents: [:sql-jdbc :metabase.driver.sql-jdbc.execute.legacy-impl/use-legacy-classes-for-read-and-set]) 🚚
[b3666a63-6251-4a47-b042-cb2408e18c67] 2021-08-17T17:58:22-05:00 ERROR metabase.driver.util Database connection error
clojure.lang.ExceptionInfo: null {:classloader #object[clojure.lang.DynamicClassLoader 0x26722665 "clojure.lang.DynamicClassLoader@26722665"], :classpath-urls ("file:/plugins/athena.metabase-driver.jar"), :system-classpath ("/app/metabase.jar")}
	at metabase.plugins.classloader$require.invokeStatic(classloader.clj:129)
	at metabase.plugins.classloader$require.doInvoke(classloader.clj:112)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at metabase.plugins.init_steps$fn__78587.invokeStatic(init_steps.clj:21)
	at metabase.plugins.init_steps$fn__78587.invoke(init_steps.clj:19)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at metabase.plugins.init_steps$do_init_steps_BANG_.invokeStatic(init_steps.clj:31)
	at metabase.plugins.init_steps$do_init_steps_BANG_.invoke(init_steps.clj:26)
	at metabase.plugins.lazy_loaded_driver$make_initialize_BANG_$fn__78626$fn__78627.invoke(lazy_loaded_driver.clj:56)
	at metabase.plugins.lazy_loaded_driver$make_initialize_BANG_$fn__78626.invoke(lazy_loaded_driver.clj:55)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at metabase.driver.impl$initialize_if_needed_BANG_.invokeStatic(impl.clj:210)
	at metabase.driver.impl$initialize_if_needed_BANG_.invoke(impl.clj:191)
	at metabase.driver$the_initialized_driver.invokeStatic(driver.clj:146)
	at metabase.driver$the_initialized_driver.invoke(driver.clj:142)
	at metabase.driver$dispatch_on_initialized_driver.invokeStatic(driver.clj:154)
	at metabase.driver$dispatch_on_initialized_driver.doInvoke(driver.clj:149)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at metabase.driver.util$can_connect_with_details_QMARK_$fn__29859.invoke(util.clj:34)
	at metabase.util$do_with_timeout$fn__15630.invoke(util.clj:346)
	at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at clojure.lang.RT.classForName(RT.java:2211)
	at clojure.lang.RT.classForName(RT.java:2220)
	at clojure.lang.RT.loadClassForName(RT.java:2239)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6839.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6780.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.core$require.doInvoke(core.clj:6007)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.plugins.classloader$require.invokeStatic(classloader.clj:127)
	... 26 more
Caused by: java.lang.ClassCastException: class clojure.lang.Var$Unbound cannot be cast to class clojure.lang.MultiFn (clojure.lang.Var$Unbound and clojure.lang.MultiFn are in unnamed module of loader 'app')
	at metabase.driver.athena__init.load(Unknown Source)
	at metabase.driver.athena__init.<clinit>(Unknown Source)
	... 54 more
[b3666a63-6251-4a47-b042-cb2408e18c67] 2021-08-17T17:58:22-05:00 INFO metabase.driver.impl Initializing driver :metabase.driver.sql-jdbc.execute.legacy-impl/use-legacy-classes-for-read-and-set...
[b3666a63-6251-4a47-b042-cb2408e18c67] 2021-08-17T17:58:22-05:00 ERROR metabase.api.database Cannot connect to Database
java.lang.Exception: 
	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:39)
	at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:22)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at metabase.api.database$test_database_connection.invokeStatic(database.clj:401)
	at metabase.api.database$test_database_connection.doInvoke(database.clj:391)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at metabase.api.database$fn__64755$test_connection_details__64760$fn__64761.invoke(database.clj:448)
	at metabase.api.database$fn__64755$test_connection_details__64760.invoke(database.clj:430)
	at metabase.api.database$fn__64790.invokeStatic(database.clj:497)
	at metabase.api.database$fn__64790.invoke(database.clj:490)
	at compojure.core$wrap_response$fn__1996.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__1980.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__1985.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:151)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:153)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:152)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:152)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:152)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:153)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:152)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008.invoke(core.clj:200)
	at metabase.server.middleware.auth$enforce_authentication$fn__77067.invoke(auth.clj:14)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008.invoke(core.clj:200)
	at compojure.core$make_context$handler__2036.invoke(core.clj:287)
	at compojure.core$make_context$fn__2038.invoke(core.clj:296)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at metabase.api.routes$fn__77133$fn__77135.invoke(routes.clj:70)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.server.routes$fn__79369$fn__79370.doInvoke(routes.clj:57)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008.invoke(core.clj:200)
	at compojure.core$make_context$handler__2036.invoke(core.clj:287)
	at compojure.core$make_context$fn__2038.invoke(core.clj:296)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:153)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:153)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:153)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at metabase.server.routes$fn__79357$fn__79359.invoke(routes.clj:41)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__77124.invoke(exceptions.clj:98)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__77121.invoke(exceptions.clj:86)
	at metabase.server.middleware.log$log_api_call$fn__79283$fn__79284$fn__79285.invoke(log.clj:209)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)
	at metabase.server.middleware.log$log_api_call$fn__79283$fn__79284.invoke(log.clj:201)
	at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
	at toucan.db$_do_with_call_counting.invoke(db.clj:209)
	at metabase.server.middleware.log$log_api_call$fn__79283.invoke(log.clj:200)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__78902.invoke(browser_cookie.clj:30)
	at metabase.server.middleware.security$add_security_headers$fn__57732.invoke(security.clj:148)
	at metabase.server.middleware.json$wrap_json_body$fn__79047.invoke(json.clj:62)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__79065.invoke(json.clj:98)
	at metabase.server.middleware.offset_paging$handle_paging$fn__57754.invoke(offset_paging.clj:42)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__79626.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__79642.invoke(params.clj:69)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__36092.invoke(misc.clj:59)
	at metabase.server.middleware.session$bind_current_user$fn__42987$fn__42988.invoke(session.clj:257)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:238)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:230)
	at metabase.server.middleware.session$bind_current_user$fn__42987.invoke(session.clj:256)
	at metabase.server.middleware.session$wrap_current_user_info$fn__42974.invoke(session.clj:216)
	at metabase.server.middleware.session$wrap_session_id$fn__42960.invoke(session.clj:162)
	at metabase.server.middleware.auth$wrap_api_key$fn__77075.invoke(auth.clj:27)
	at ring.middleware.cookies$wrap_cookies$fn__79546.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__36075.invoke(misc.clj:27)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__36100.invoke(misc.clj:76)
	at ring.middleware.gzip$wrap_gzip$fn__79588.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__36103.invoke(misc.clj:93)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__79302.invoke(ssl.clj:38)
	at metabase.server$async_proxy_handler$fn__78846.invoke(server.clj:71)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: clojure.lang.ExceptionInfo: null {:classloader #object[clojure.lang.DynamicClassLoader 0x26722665 "clojure.lang.DynamicClassLoader@26722665"], :classpath-urls ("file:/plugins/athena.metabase-driver.jar"), :system-classpath ("/app/metabase.jar")}
	at metabase.plugins.classloader$require.invokeStatic(classloader.clj:129)
	at metabase.plugins.classloader$require.doInvoke(classloader.clj:112)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at metabase.plugins.init_steps$fn__78587.invokeStatic(init_steps.clj:21)
	at metabase.plugins.init_steps$fn__78587.invoke(init_steps.clj:19)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at metabase.plugins.init_steps$do_init_steps_BANG_.invokeStatic(init_steps.clj:31)
	at metabase.plugins.init_steps$do_init_steps_BANG_.invoke(init_steps.clj:26)
	at metabase.plugins.lazy_loaded_driver$make_initialize_BANG_$fn__78626$fn__78627.invoke(lazy_loaded_driver.clj:56)
	at metabase.plugins.lazy_loaded_driver$make_initialize_BANG_$fn__78626.invoke(lazy_loaded_driver.clj:55)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at metabase.driver.impl$initialize_if_needed_BANG_.invokeStatic(impl.clj:210)
	at metabase.driver.impl$initialize_if_needed_BANG_.invoke(impl.clj:191)
	at metabase.driver$the_initialized_driver.invokeStatic(driver.clj:146)
	at metabase.driver$the_initialized_driver.invoke(driver.clj:142)
	at metabase.driver$dispatch_on_initialized_driver.invokeStatic(driver.clj:154)
	at metabase.driver$dispatch_on_initialized_driver.doInvoke(driver.clj:149)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at metabase.driver.util$can_connect_with_details_QMARK_$fn__29859.invoke(util.clj:34)
	at metabase.util$do_with_timeout$fn__15630.invoke(util.clj:346)
	at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
Caused by: java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at clojure.lang.RT.classForName(RT.java:2211)
	at clojure.lang.RT.classForName(RT.java:2220)
	at clojure.lang.RT.loadClassForName(RT.java:2239)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6839.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6780.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.core$require.doInvoke(core.clj:6007)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.plugins.classloader$require.invokeStatic(classloader.clj:127)
	... 26 more
Caused by: java.lang.ClassCastException: class clojure.lang.Var$Unbound cannot be cast to class clojure.lang.MultiFn (clojure.lang.Var$Unbound and clojure.lang.MultiFn are in unnamed module of loader 'app')
	at metabase.driver.athena__init.load(Unknown Source)
	at metabase.driver.athena__init.<clinit>(Unknown Source)
	... 54 more
```

Below is the system diagnostic.

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "5.4.129-63.229.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-08-03",
      "tag": "v0.40.2",
      "branch": "release-x.40.x",
      "hash": "b884d29"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by drew-flintosh** [comment]
Follow up: I did roll Metabase back to v.0.36.12 and the Athena driver did work.

**Comment by dacort** [comment]
Hey there - can you make sure you're using v1.2.1 of the driver with Metabase v0.40.2?

I hadn't updated the Dockerfile with the most recent release unfortunately.

**Comment by drew-flintosh** [comment]
That absolutely worked. Apologies for not looking closer to what I was copying and thanks for the reply!
